### ISSUE TITLE
Cannot read property path

### ISSUE THREAD

**Issue by danger89** [mpashkovskiy/express-oas-generator#1]
During `npm start`.

I get:

```
..../node_modules/express-oas-generator/index.js:44
      let path = prefix + route.route.path;
                                      ^

TypeError: Cannot read property 'path' of undefined
    at stack.forEach.route (..../node_modules/express-oas-generator/index.js:44:39)
    at Array.forEach (<anonymous>)
    at app._router.stack.forEach.router (..../node_modules/express-oas-generator/index.js:42:11)
    at Array.forEach (<anonymous>)
    at init (..../node_modules/express-oas-generator/index.js:34:21)
    at Timeout.setTimeout [as _onTimeout] (..../node_modules/express-oas-generator/index.js:162:5)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

```

**Comment by mpashkovskiy** [comment]
Could you please elaborate a bit more on how you initialize express app and routers in it so I can fix the module?

**Comment by danger89** [comment]
Sure.

File `app.js`:
```js
var express = require('express')
var apiRouter = express.Router()
var index = require('./routes/index')
var user = require('./routes/user')

var app = express()

// API routes
apiRouter.get('/', index)
apiRouter.use('/users', user)

app.use('/', index)
app.use('/api/v1', apiRouter)
```

Example of `index.js` file:
```js
var express = require('express')
var router = express.Router()

router.get('/', function (req, res, next) {
  res.status(200).json({'status': 200, 'response': {'message': 'Test string'}})
})

module.exports = router
```

Similar get, post, put & delete methods are attached to the user.js file.

**Comment by mpashkovskiy** [comment]
Tried to reproduce the problem in develop branch (see https://github.com/mpashkovskiy/express-oas-generator/blob/develop/issue_1.js) but with no luck. Did I configure something wrong?
Which version of module do you use? I'm trying it with is 0.1.12

Also I added extra check so could you please try with 0.1.13?

**Comment by mpashkovskiy** [comment]
I suppose problem is solved, so closing the issue.
