### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by jdnichollsc** [mpashkovskiy/express-oas-generator#11]
Hi man,
I'm trying to use this library but I have the following issue from the console
```
TypeError: Cannot read property 'forEach' of undefined
index.js:36
    at getEndpoints (/Users/jdnichollsc/dev/enturnate/enturnate-api/node_modules/express-list-endpoints/src/index.js:36:9)
    at /Users/jdnichollsc/dev/enturnate/enturnate-api/node_modules/express-list-endpoints/src/index.js:65:9
    at Array.forEach (<anonymous>)
    at getEndpoints (/Users/jdnichollsc/dev/enturnate/enturnate-api/node_modules/express-list-endpoints/src/index.js:36:9)
    at init (/Users/jdnichollsc/dev/enturnate/enturnate-api/node_modules/express-oas-generator/index.js:37:21)
    at Timeout.setTimeout [as _onTimeout] (/Users/jdnichollsc/dev/enturnate/enturnate-api/node_modules/express-oas-generator/index.js:166:5)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

And the `app` value is:
```
[[FunctionLocation]]:internal#location
[[Scopes]]:Scopes[3]
arguments:TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
caller:TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
length:3
name:""
```

Let me know what you think

Thanks in advance, Nicholls

**Comment by jdnichollsc** [comment]
@mpashkovskiy the last one
Thanks in advance!

**Comment by mpashkovskiy** [comment]
Hi Nicholls, the problem is related to the fact that there is no **stack** or **_router** or **_router.stack** field defined for the variable **app** passed to the module. It is thrown by one of the dependencies of my module. Here is the line: https://github.com/AlbertoFdzM/express-list-endpoints/blob/develop/src/index.js#L36
Are you sure that you pass ExpressJS app to the module? Which version of ExpressJS are you using?

**Comment by jdnichollsc** [comment]
Thanks @mpashkovskiy for your response!
Ohh this library is having issues with this other library to use ES6 with Express https://github.com/davidbanham/express-async-errors

**Comment by jdnichollsc** [comment]
Check my package.json:

```
var express = require('express');
//require('express-async-errors');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var cors = require('cors');
var expressOasGenerator = require('express-oas-generator');

var indexRoute = require('./routes/index');
var userRoute = require('./routes/user');
var authRoute = require('./routes/auth');
var vehicleRoute = require('./routes/vehicle');
var availableRoute = require('./routes/available');
var departamentRoute = require('./routes/departament');
var municipalityRoute = require('./routes/municipality');
var destinyRoute = require('./routes/destiny');

var app = express();
app.use(cors());

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRoute);
app.use('/users', userRoute);
app.use('/auth', authRoute);
app.use('/vehicles', vehicleRoute);
app.use('/available', availableRoute);
app.use('/departament', departamentRoute);
app.use('/municipality', municipalityRoute);
app.use('/destiny', destinyRoute);
expressOasGenerator.init(app, {});

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
```

Let me know what you think, thanks for all!

**Comment by mpashkovskiy** [comment]
I suppose it is not relevant anymore. Please reopen if it is still an issue.

**Comment by satyamskillz** [comment]
I am still facing this issue. What is the solution? Please explain!
