### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by ddska** [mpashkovskiy/express-oas-generator#3]
Sometimes my REST API fails with this error: 

```
/usr/src/bff/node_modules/express-oas-generator/lib/processors.js:122
  const body = JSON.parse(Buffer.concat(chunks).toString('utf8'));
                    ^
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at updateResponses (/usr/src/bff/node_modules/express-oas-generator/lib/processors.js:122:21)
    at ServerResponse.res.end (/usr/src/bff/node_modules/express-oas-generator/lib/processors.js:156:9)
    at Gzip.onStreamEnd (/usr/src/bff/node_modules/compression/index.js:212:14)
    at emitNone (events.js:111:20)
    at Gzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
```

I have not understood how to reproduce it yet, but may be a trim and try-catch would be helpful here.

**Comment by mpashkovskiy** [comment]
Thanks for reporting. Checking...
